default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: fablogger_development
  username: fablogger
  password: <%= ENV['DATABASE_PASSWORD'] %>


test:
  <<: *default
  database: fablogger_test 

production:
  <<: *default
  database: fablogger_production
  username: fablogger 
  password: <%= ENV['DATABASE_PASSWORD'] %>


