# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 60820cda6e7853b5d74fa97e8552893d75af3ec5dac26e21329c60d80543c70aa24d8405c67ef31593943ea9e62c6ad21bc9785dc8ffcf637485a0f0f111a5ea

test:
  secret_key_base: 316a4dd126d645dc4105c9465d07d03593e1cf37e61fe5f59971e1d4ace5224b9586b8b2e3aa95eab91e7185f97e1c7e5fcc5995a60f0b8f788facd1ce173a4e

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
